/*
 * One drill screen, and the five-state machine the spec's run lifecycle table describes.
 *
 * That table IS this file: which button is enabled, what the grid shows, and what a state
 * change does are the whole of what is written here. Everything a drill actually decides -
 * what a set is made of, what a tap does to a cell, whether that cell shows its value, what
 * the tally reads - is asked of DrillOps and DrillRun, so this screen holds no rule that a
 * JVM test would want to reach and none that could disagree with the stats table about the
 * same run. The lone exception is how big a generated set may get, which is a question about
 * this frame rather than about the drill: see freshItems, and DrillGrid's column clamp for the
 * same argument made about the same kind of hand-edit.
 *
 * The clock is the one thing here that no pure layer can own: it reads the wall clock, which
 * is exactly why the pure layer takes elapsed time as a number instead.
 */
package net.jacoblo.simpleanki.drill

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.RowScope
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalLifecycleOwner
import androidx.compose.ui.unit.dp
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleEventObserver
import kotlinx.coroutines.delay
import net.jacoblo.simpleanki.data.DrillItem
import net.jacoblo.simpleanki.data.DrillRun
import net.jacoblo.simpleanki.data.Settings
import java.util.Locale
import kotlin.random.Random

/**
 * The five states of a drill screen, one per row of the spec's run lifecycle table.
 *
 * [PAST_RUN] is an entry state rather than a mode: pressing Edit on an opened run drops it to
 * [FINISHED], and the next Edit brings up [EDITING], which is the same view with the same
 * autosave behind it. The three share a button row exactly, so nothing is lost by the fall -
 * and what must be preserved, that Start and Done stay dead for a run whose time is already
 * history, is preserved by both of them being off in all three.
 */
enum class DrillState { FRESH, RUNNING, FINISHED, EDITING, PAST_RUN }

/**
 * A drill: the clock, the grid, and the five buttons.
 *
 * @param settings read for the item count and the grid shape, and read on EVERY composition
 *   rather than captured. What is deliberately NOT keyed on it is the generated set: the app
 *   reloads settings.json on every resume, so a set remembered against this object would be
 *   regenerated by the very backgrounding that is supposed to leave it alone. The item count is
 *   capped on the way past - see [freshItems] - so a set is not always the size the file names.
 * @param openRun non-null when a stored run is being re-scored. Its items and duration are
 *   shown and Start/Done are dead - the run's time is history.
 * @param onDone raised when the clock stops, with the finished run. The caller stores it.
 * @param onItemsChanged raised on every scoring tap, with the run as it now stands. Carries
 *   the whole run and not a diff, because the caller rewrites the record wholesale.
 * @param onCloseRun raised by New, which is the only way out of an opened run. The caller owes
 *   it a null [openRun] in reply; until it arrives this screen already shows a fresh set.
 */
@Composable
fun DrillScreen(
	kind: DrillKind,
	settings: Settings,
	openRun: DrillRun?,
	onDone: (DrillRun) -> Unit,
	onItemsChanged: (DrillRun) -> Unit,
	onOpenPicker: () -> Unit,
	onCloseRun: () -> Unit,
	modifier: Modifier = Modifier
) {
	// Every slot below is keyed on [kind], and the key is load-bearing rather than tidy.
	// remember is positional, and both drills are headed for ONE call site: a single screen
	// carrying the kind, so picking the other drill out of the drawer changes this argument
	// and REUSES these slots. Unkeyed, the Poker set would stay on screen while the grid
	// switched to the Numbers shape, and an opened Poker run would survive into a Numbers
	// screen intact - the adoption effect below cannot undo it, since it no-ops on a null id.
	// Keyed, changing drill is what it looks like: a fresh set of the new drill, in FRESH,
	// with the clock at zero.
	//
	// Deliberately NOT keyed on [settings] as well - see that parameter's note.
	var items by remember(kind) { mutableStateOf(freshItems(kind, settings)) }
	var state by remember(kind) { mutableStateOf(DrillState.FRESH) }
	// The wall clock at Start, which is also the run's identity. Zero until the first Start.
	var startedAt by remember(kind) { mutableStateOf(0L) }
	// Elapsed time as the timer shows it: ticking while RUNNING, frozen everywhere else.
	var seconds by remember(kind) { mutableStateOf(0f) }
	// The id of the opened run, or null for a live one. Kept rather than re-derived because a
	// hand-edited file may carry an id that is not its startedAt, and rewriting that run under
	// the id this screen would have minted appends a second record instead of updating the one
	// being scored.
	var openId by remember(kind) { mutableStateOf<String?>(null) }

	// Cells are tappable, and the tally is shown, in exactly these two states.
	val scoring = state == DrillState.EDITING || state == DrillState.PAST_RUN
	// Marks drawn, unmarked cells hidden. True in FRESH as well, which is how a fresh set is
	// covered - see the note at the DrillGrid call. A DIFFERENT question from [scoring] above,
	// and named apart from it deliberately: the two are equal in every state but FRESH, so one
	// name over both would read as a tidy-up waiting to happen and reveal the set before Start.
	val hideUnmarked = state != DrillState.RUNNING && state != DrillState.FINISHED

	/**
	 * The run on screen, carrying [marked] as its items.
	 *
	 * The id falls back to the start timestamp for a live run, which is the invariant Models
	 * documents - and this is the place runs are minted, so this is where it has to hold.
	 */
	fun runWith(marked: List<DrillItem>): DrillRun =
		DrillRun(openId ?: startedAt.toString(), startedAt, seconds, marked)

	/** New, and the state every drill screen opens in. */
	fun freshSet() {
		items = freshItems(kind, settings)
		state = DrillState.FRESH
		startedAt = 0L
		seconds = 0f
		openId = null
		// Unconditional: New is the escape hatch out of an opened run, and a caller still
		// holding one would hand it straight back through the effect below.
		onCloseRun()
	}

	// Adopting an opened run, and RELEASING one the caller has dropped. Keyed on the id and
	// NOT on the run itself, because the caller may well hand back the run this screen just
	// autosaved: keyed on the object, every scoring tap would re-adopt and shove the screen
	// back to PAST_RUN mid-edit.
	//
	// The release half is what makes the drawer entry for the drill you are ALREADY on do
	// anything. It hands back Screen.Drill(kind, null), the same null DrillRoute resolves an
	// unopenable id to - and an effect that could only adopt would leave the past run's grid on
	// screen with its clock still frozen and Start and Done still dead, New being the one way
	// out of a drill the user had just asked for by name.
	LaunchedEffect(openRun?.id) {
		val run = openRun
		if (run == null) {
			// The caller dropped the open run: the drawer re-selecting this drill, or a
			// hand-edit that removed the run from the file. A fresh live drill is what
			// DrillRoute documents that null as meaning, so fall back to one.
			//
			// Guarded on [openId], and the guard is the load-bearing half. The caller's run
			// list starts EMPTY and is filled by the ON_RESUME its observer is added by, so
			// the first frame of a stats-row tap or a picked run has openRun null with the id
			// already in the screen argument. Unguarded, that frame would call freshSet and
			// bounce the caller back to Screen.Drill(kind, null), and the run the user asked
			// for would never get to adopt at all. Releasing needs a run to release.
			//
			// It ends the only path back here as well. freshSet raises onCloseRun, whose reply
			// is the very Screen.Drill(kind, null) that got here - equal to what the caller
			// already holds, so the assignment does not even invalidate - and were it to
			// arrive anyway, null is already this effect's key, so it does not re-key and this
			// branch is not re-entered. Three separate reasons it cannot loop.
			if (openId != null) freshSet()
			return@LaunchedEffect
		}
		items = run.items
		startedAt = run.startedAt
		seconds = run.seconds
		openId = run.id
		state = DrillState.PAST_RUN
	}

	// The clock. Recomputed from the wall clock on every tick rather than accumulated, so a
	// recomposition, a slow frame, or a delay that overshoots cannot drift the recorded time.
	// Keyed on the state and on nothing else. Leaving RUNNING is what stops it - Done, New,
	// and backgrounding all leave - and cancels this coroutine mid-delay. startedAt is no key
	// of its own: it is read live off the delegate, and Start is its only writer that a tick
	// could race, which the guard on FRESH keeps out of RUNNING entirely.
	LaunchedEffect(state) {
		if (state != DrillState.RUNNING) return@LaunchedEffect
		while (true) {
			seconds = (System.currentTimeMillis() - startedAt) / MILLIS_PER_SECOND
			delay(TICK_MILLIS)
			// Tested again AFTER the delay as well as before the loop. Cancellation arrives
			// with the recomposition Done triggers, so a tick coming due in the frame Done was
			// pressed in still gets its turn - and would write one more elapsed time over the
			// frozen one, leaving the timer a second ahead of the run that was just stored.
			if (state != DrillState.RUNNING) return@LaunchedEffect
		}
	}

	// Backgrounding abandons a run in progress: same set, clock back to zero, ready to be
	// attempted again. Composition survives backgrounding, so nothing but this observer can
	// tell the screen the app went away - the same reason MainActivity keeps one. Rotation
	// arrives as a pause too, which is the spec's intent: a timed run does not survive it.
	val lifecycleOwner = LocalLifecycleOwner.current
	DisposableEffect(lifecycleOwner) {
		val observer = LifecycleEventObserver { _, event ->
			// RUNNING alone. Every other state is already stored, so there is nothing to
			// abandon, and re-covering the set would throw away marks the user is mid-way
			// through making.
			if (event == Lifecycle.Event.ON_PAUSE && state == DrillState.RUNNING) {
				state = DrillState.FRESH
				startedAt = 0L
				seconds = 0f
			}
		}
		lifecycleOwner.lifecycle.addObserver(observer)
		onDispose { lifecycleOwner.lifecycle.removeObserver(observer) }
	}

	Column(
		modifier = modifier
			.fillMaxSize()
			.padding(16.dp),
		horizontalAlignment = Alignment.CenterHorizontally
	) {
		Text(text = DrillOps.minutesSeconds(seconds), style = MaterialTheme.typography.headlineMedium)
		// The tally is a scoring instrument: outside scoring every cell reads unscored, so
		// showing it in Fresh or Running would report 0% at a set nobody has marked yet.
		if (scoring) {
			Text(text = tally(runWith(items)), style = MaterialTheme.typography.bodyLarge)
		}
		DrillGrid(
			items = items,
			geometry = kind.geometry(settings),
			// True while scoring AND in FRESH, which is not a fudge. DrillOps.isRevealed
			// hides an unmarked cell exactly when this is set, a Fresh set is entirely
			// unmarked, and covering it is the whole of what Fresh means. Passing false there
			// would reveal the set before Start, which is the one thing that must not happen:
			// Start revealing it is what makes the recorded time mean anything.
			scoring = hideUnmarked,
			redValue = DrillOps::isRedSuit,
			onTap = if (!scoring) null else ({ index ->
				val marked = DrillOps.cycle(items, index)
				items = marked
				// Every tap, with the run as it now stands. There is no save button and
				// nothing is ever left pending, matching views, widths, and settings.
				onItemsChanged(runWith(marked))
			}),
			modifier = Modifier.weight(1f)
		)
		Row(
			modifier = Modifier
				.fillMaxWidth()
				.padding(top = 8.dp),
			horizontalArrangement = Arrangement.spacedBy(4.dp)
		) {
			DrillButton(label = "Start", enabled = state == DrillState.FRESH) {
				// Guarded like Done, and for the same reason: a second tap landing before the
				// recomposition that disables this button would restart the clock on a run
				// already under way, quietly shortening the time it records.
				if (state != DrillState.FRESH) return@DrillButton
				startedAt = System.currentTimeMillis()
				seconds = 0f
				state = DrillState.RUNNING
			}
			DrillButton(label = "Done", enabled = state == DrillState.RUNNING) {
				// The guard, not the enabled flag, is what makes this fire once. `enabled` is
				// read from the last composition, so two taps inside one frame both reach
				// this lambda - and the second would store the run a second time under a
				// second id. Reading the state here reads it as it stands now.
				if (state != DrillState.RUNNING) return@DrillButton
				val elapsed = (System.currentTimeMillis() - startedAt) / MILLIS_PER_SECOND
				seconds = elapsed
				state = DrillState.FINISHED
				// id == startedAt.toString(), the invariant Models.kt documents. Built here
				// rather than through runWith so it cannot depend on a state write landing
				// before the read that follows it.
				onDone(DrillRun(startedAt.toString(), startedAt, elapsed, items))
			}
			// Enabled in every state, including over an opened run, and it discards what is on
			// screen without a confirmation. Nothing is lost that was not already stored: a
			// run reaches storage at Done and every scoring tap rewrites it, so the only thing
			// New can throw away is an attempt the user chose to abandon.
			DrillButton(label = "New", enabled = true) { freshSet() }
			DrillButton(label = "Edit", enabled = state == DrillState.FINISHED || scoring) {
				state = when (state) {
					DrillState.FINISHED -> DrillState.EDITING
					// Toggling off returns the revealed Finished view. The marks are not
					// discarded - the grid simply stops drawing them - so the next Edit
					// brings back every one of them.
					DrillState.EDITING, DrillState.PAST_RUN -> DrillState.FINISHED
					// Unreachable: the button is disabled in both. A no-op rather than a
					// throw, and spelled out rather than left to an else, so a sixth state
					// would have to answer here instead of silently doing nothing.
					DrillState.FRESH, DrillState.RUNNING -> state
				}
			}
			DrillButton(label = "Runs", enabled = true) { onOpenPicker() }
		}
	}
}

/**
 * One button of the row, sized by weight so all five share the width evenly.
 *
 * Disabled, never hidden: the row keeps its shape in every state, so the user learns where
 * Done is rather than watching the buttons shuffle under their thumb. The content padding is
 * cut right down because five default buttons do not fit across a 360dp phone.
 */
@Composable
private fun RowScope.DrillButton(label: String, enabled: Boolean, onClick: () -> Unit) {
	Button(
		onClick = onClick,
		enabled = enabled,
		modifier = Modifier.weight(1f),
		contentPadding = PaddingValues(horizontal = 2.dp, vertical = 8.dp)
	) {
		Text(text = label, maxLines = 1, style = MaterialTheme.typography.labelMedium)
	}
}

/**
 * A fresh set for [kind], capped at [MAX_DRILL_ITEMS].
 *
 * The cap is here, where the count is consumed, and not in [DrillKind.itemCount], which passes
 * the stored figure through unvalidated on purpose - both of their notes carry the argument. The
 * low end is deliberately untouched: a zero or a negative generates nothing and the grid comes up
 * empty, which is the honest picture of what the file says and is not a crash, because
 * DrillOps.generateNumbers builds from a range precisely so that it is not.
 *
 * Only a GENERATED set is capped. A stored run carrying an absurd items list is adopted whole,
 * because those items are written straight back by the next scoring tap and truncating them for
 * the grid would turn a display problem into deleted data.
 */
private fun freshItems(kind: DrillKind, settings: Settings): List<DrillItem> =
	DrillOps.generate(kind, kind.itemCount(settings).coerceAtMost(MAX_DRILL_ITEMS), Random.Default)

/**
 * The live tally, `40/50 = 80%`.
 *
 * Both figures come off the run rather than being counted here, so the percentage on screen
 * and the one in the stats table are the same rule - including that the denominator is the
 * whole count, which makes an unchecked item cost exactly what a missed one does.
 *
 * The percentage is dropped for an empty run, which only a hand-edited count of zero reaches.
 */
private fun tally(run: DrillRun): String {
	val accuracy = run.accuracy ?: return "${run.right}/${run.count}"
	return "%d/%d = %.0f%%".format(Locale.ROOT, run.right, run.count, accuracy * 100)
}


private const val MILLIS_PER_SECOND = 1000f

/**
 * Four ticks a second. The display is whole seconds, so this is only ever about how late a
 * second appears; recomputing from the wall clock means it cannot be about how much time the
 * run is recorded as taking.
 */
private const val TICK_MILLIS = 250L
