/*
 * One drill screen, and the five-state machine the spec's run lifecycle table describes.
 *
 * That table IS this file: which button is enabled, what the grid shows, and what a state
 * change does are the whole of what is written here. Everything a drill actually decides -
 * what a set is made of, what a tap does to a cell, whether that cell shows its value, what
 * the tally reads - is asked of DrillOps and DrillRun, so this screen holds no rule that a
 * JVM test would want to reach and none that could disagree with the stats table about the
 * same run.
 *
 * The clock is the one thing here that no pure layer can own: it reads the wall clock, which
 * is exactly why the pure layer takes elapsed time as a number instead.
 */
package net.jacoblo.simpleanki.drill

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.PaddingValues
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.RowScope
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.material3.Button
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.DisposableEffect
import androidx.compose.runtime.LaunchedEffect
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.platform.LocalLifecycleOwner
import androidx.compose.ui.unit.dp
import androidx.lifecycle.Lifecycle
import androidx.lifecycle.LifecycleEventObserver
import kotlinx.coroutines.delay
import net.jacoblo.simpleanki.data.DrillItem
import net.jacoblo.simpleanki.data.DrillRun
import net.jacoblo.simpleanki.data.Settings
import java.util.Locale
import kotlin.random.Random

/**
 * The five states of a drill screen, one per row of the spec's run lifecycle table.
 *
 * [PAST_RUN] is an entry state rather than a mode: pressing Edit on an opened run drops it to
 * [FINISHED], and the next Edit brings up [EDITING], which is the same view with the same
 * autosave behind it. The three share a button row exactly, so nothing is lost by the fall -
 * and what must be preserved, that Start and Done stay dead for a run whose time is already
 * history, is preserved by both of them being off in all three.
 */
enum class DrillState { FRESH, RUNNING, FINISHED, EDITING, PAST_RUN }

/**
 * A drill: the clock, the grid, and the five buttons.
 *
 * @param settings read for the item count and the grid shape, and read on EVERY composition
 *   rather than captured. What is deliberately NOT keyed on it is the generated set: the app
 *   reloads settings.json on every resume, so a set remembered against this object would be
 *   regenerated by the very backgrounding that is supposed to leave it alone.
 * @param openRun non-null when a stored run is being re-scored. Its items and duration are
 *   shown and Start/Done are dead - the run's time is history.
 * @param onDone raised when the clock stops, with the finished run. The caller stores it.
 * @param onItemsChanged raised on every scoring tap, with the run as it now stands. Carries
 *   the whole run and not a diff, because the caller rewrites the record wholesale.
 * @param onCloseRun raised by New, which is the only way out of an opened run. The caller owes
 *   it a null [openRun] in reply; until it arrives this screen already shows a fresh set.
 */
@Composable
fun DrillScreen(
	kind: DrillKind,
	settings: Settings,
	openRun: DrillRun?,
	onDone: (DrillRun) -> Unit,
	onItemsChanged: (DrillRun) -> Unit,
	onOpenPicker: () -> Unit,
	onCloseRun: () -> Unit,
	modifier: Modifier = Modifier
) {
	// Generated once, on the way in, so the shape and scale of what is coming is on screen
	// before the clock starts. No keys, for the reason given on the settings parameter.
	var items by remember { mutableStateOf(DrillOps.generate(kind, kind.itemCount(settings), Random.Default)) }
	var state by remember { mutableStateOf(DrillState.FRESH) }
	// The wall clock at Start, which is also the run's identity. Zero until the first Start.
	var startedAt by remember { mutableStateOf(0L) }
	// Elapsed time as the timer shows it: ticking while RUNNING, frozen everywhere else.
	var seconds by remember { mutableStateOf(0f) }
	// The id of the opened run, or null for a live one. Kept rather than re-derived because a
	// hand-edited file may carry an id that is not its startedAt, and rewriting that run under
	// the id this screen would have minted appends a second record instead of updating the one
	// being scored.
	var openId by remember { mutableStateOf<String?>(null) }

	// Cells are tappable, and the tally is shown, in exactly these two states.
	val scoring = state == DrillState.EDITING || state == DrillState.PAST_RUN

	/**
	 * The run on screen, carrying [marked] as its items.
	 *
	 * The id falls back to the start timestamp for a live run, which is the invariant Models
	 * documents - and this is the place runs are minted, so this is where it has to hold.
	 */
	fun runWith(marked: List<DrillItem>): DrillRun =
		DrillRun(openId ?: startedAt.toString(), startedAt, seconds, marked)

	/** New, and the state every drill screen opens in. */
	fun freshSet() {
		items = DrillOps.generate(kind, kind.itemCount(settings), Random.Default)
		state = DrillState.FRESH
		startedAt = 0L
		seconds = 0f
		openId = null
		// Unconditional: New is the escape hatch out of an opened run, and a caller still
		// holding one would hand it straight back through the effect below.
		onCloseRun()
	}

	// Adopting an opened run. Keyed on the id and NOT on the run itself, because the caller
	// may well hand back the run this screen just autosaved: keyed on the object, every
	// scoring tap would re-adopt and shove the screen back to PAST_RUN mid-edit. A null id
	// does nothing at all - the caller reaching null is New's own doing, already handled.
	LaunchedEffect(openRun?.id) {
		val run = openRun ?: return@LaunchedEffect
		items = run.items
		startedAt = run.startedAt
		seconds = run.seconds
		openId = run.id
		state = DrillState.PAST_RUN
	}

	// The clock. Recomputed from the wall clock on every tick rather than accumulated, so a
	// recomposition, a slow frame, or a delay that overshoots cannot drift the recorded time.
	// Keyed on the state, which is what stops it: Done, New, and backgrounding all leave
	// RUNNING, and leaving RUNNING cancels this coroutine mid-delay.
	LaunchedEffect(state, startedAt) {
		if (state != DrillState.RUNNING) return@LaunchedEffect
		while (true) {
			seconds = (System.currentTimeMillis() - startedAt) / MILLIS_PER_SECOND
			delay(TICK_MILLIS)
		}
	}

	// Backgrounding abandons a run in progress: same set, clock back to zero, ready to be
	// attempted again. Composition survives backgrounding, so nothing but this observer can
	// tell the screen the app went away - the same reason MainActivity keeps one. Rotation
	// arrives as a pause too, which is the spec's intent: a timed run does not survive it.
	val lifecycleOwner = LocalLifecycleOwner.current
	DisposableEffect(lifecycleOwner) {
		val observer = LifecycleEventObserver { _, event ->
			// RUNNING alone. Every other state is already stored, so there is nothing to
			// abandon, and re-covering the set would throw away marks the user is mid-way
			// through making.
			if (event == Lifecycle.Event.ON_PAUSE && state == DrillState.RUNNING) {
				state = DrillState.FRESH
				startedAt = 0L
				seconds = 0f
			}
		}
		lifecycleOwner.lifecycle.addObserver(observer)
		onDispose { lifecycleOwner.lifecycle.removeObserver(observer) }
	}

	Column(
		modifier = modifier
			.fillMaxSize()
			.padding(16.dp),
		horizontalAlignment = Alignment.CenterHorizontally
	) {
		Text(text = minutesSeconds(seconds), style = MaterialTheme.typography.headlineMedium)
		// The tally is a scoring instrument: outside scoring every cell reads unscored, so
		// showing it in Fresh or Running would report 0% at a set nobody has marked yet.
		if (scoring) {
			Text(text = tally(runWith(items)), style = MaterialTheme.typography.bodyLarge)
		}
		DrillGrid(
			items = items,
			geometry = kind.geometry(settings),
			// True while scoring AND in FRESH, which is not a fudge. DrillOps.isRevealed
			// hides an unmarked cell exactly when this is set, a Fresh set is entirely
			// unmarked, and covering it is the whole of what Fresh means. Passing false there
			// would reveal the set before Start, which is the one thing that must not happen:
			// Start revealing it is what makes the recorded time mean anything.
			scoring = state != DrillState.RUNNING && state != DrillState.FINISHED,
			redValue = DrillOps::isRedSuit,
			onTap = if (!scoring) null else ({ index ->
				val marked = DrillOps.cycle(items, index)
				items = marked
				// Every tap, with the run as it now stands. There is no save button and
				// nothing is ever left pending, matching views, widths, and settings.
				onItemsChanged(runWith(marked))
			}),
			modifier = Modifier.weight(1f)
		)
		Row(
			modifier = Modifier
				.fillMaxWidth()
				.padding(top = 8.dp),
			horizontalArrangement = Arrangement.spacedBy(4.dp)
		) {
			DrillButton(label = "Start", enabled = state == DrillState.FRESH) {
				// Guarded like Done, and for the same reason: a second tap landing before the
				// recomposition that disables this button would restart the clock on a run
				// already under way, quietly shortening the time it records.
				if (state != DrillState.FRESH) return@DrillButton
				startedAt = System.currentTimeMillis()
				seconds = 0f
				state = DrillState.RUNNING
			}
			DrillButton(label = "Done", enabled = state == DrillState.RUNNING) {
				// The guard, not the enabled flag, is what makes this fire once. `enabled` is
				// read from the last composition, so two taps inside one frame both reach
				// this lambda - and the second would store the run a second time under a
				// second id. Reading the state here reads it as it stands now.
				if (state != DrillState.RUNNING) return@DrillButton
				val elapsed = (System.currentTimeMillis() - startedAt) / MILLIS_PER_SECOND
				seconds = elapsed
				state = DrillState.FINISHED
				// id == startedAt.toString(), the invariant Models.kt documents. Built here
				// rather than through runWith so it cannot depend on a state write landing
				// before the read that follows it.
				onDone(DrillRun(startedAt.toString(), startedAt, elapsed, items))
			}
			// Enabled in every state, including over an opened run, and it discards what is on
			// screen without a confirmation. Nothing is lost that was not already stored: a
			// run reaches storage at Done and every scoring tap rewrites it, so the only thing
			// New can throw away is an attempt the user chose to abandon.
			DrillButton(label = "New", enabled = true) { freshSet() }
			DrillButton(label = "Edit", enabled = state == DrillState.FINISHED || scoring) {
				state = when (state) {
					DrillState.FINISHED -> DrillState.EDITING
					// Toggling off returns the revealed Finished view. The marks are not
					// discarded - the grid simply stops drawing them - so the next Edit
					// brings back every one of them.
					DrillState.EDITING, DrillState.PAST_RUN -> DrillState.FINISHED
					// Unreachable: the button is disabled in both. A no-op rather than a
					// throw, and spelled out rather than left to an else, so a sixth state
					// would have to answer here instead of silently doing nothing.
					DrillState.FRESH, DrillState.RUNNING -> state
				}
			}
			DrillButton(label = "Runs", enabled = true) { onOpenPicker() }
		}
	}
}

/**
 * One button of the row, sized by weight so all five share the width evenly.
 *
 * Disabled, never hidden: the row keeps its shape in every state, so the user learns where
 * Done is rather than watching the buttons shuffle under their thumb. The content padding is
 * cut right down because five default buttons do not fit across a 360dp phone.
 */
@Composable
private fun RowScope.DrillButton(label: String, enabled: Boolean, onClick: () -> Unit) {
	Button(
		onClick = onClick,
		enabled = enabled,
		modifier = Modifier.weight(1f),
		contentPadding = PaddingValues(horizontal = 2.dp, vertical = 8.dp)
	) {
		Text(text = label, maxLines = 1, style = MaterialTheme.typography.labelMedium)
	}
}

/**
 * The live tally, `40/50 = 80%`.
 *
 * Both figures come off the run rather than being counted here, so the percentage on screen
 * and the one in the stats table are the same rule - including that the denominator is the
 * whole count, which makes an unchecked item cost exactly what a missed one does.
 *
 * The percentage is dropped for an empty run, which only a hand-edited count of zero reaches.
 */
private fun tally(run: DrillRun): String {
	val accuracy = run.accuracy ?: return "${run.right}/${run.count}"
	return "%d/%d = %.0f%%".format(Locale.ROOT, run.right, run.count, accuracy * 100)
}

/**
 * [seconds] as mm:ss, truncated the way a running stopwatch reads.
 *
 * A deliberate COPY of DrillStatsTable's formatter of the same name, which is private to it,
 * and not wrapped at 60 for the same reason: a run past the hour reads "65:00" rather than
 * the "05:00" a modulo would give it, so the stats table and the screen the run was timed on
 * never disagree about how long it took. Nothing makes the two drift together.
 */
private fun minutesSeconds(seconds: Float): String {
	val whole = seconds.toInt()
	return "%02d:%02d".format(Locale.ROOT, whole / 60, whole % 60)
}

private const val MILLIS_PER_SECOND = 1000f

/**
 * Four ticks a second. The display is whole seconds, so this is only ever about how late a
 * second appears; recomputing from the wall clock means it cannot be about how much time the
 * run is recorded as taking.
 */
private const val TICK_MILLIS = 250L
